
addons:
    apt:
      packages:
        - xvfb
  
  install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
language: node_js
sudo: eneabled
node_js:
  - "iojs"
  - "7"
  npm install electron-packager
  
  electron packager electron-packager ./ NootFlix ReFresh --platform=all --arch=all 
